import Head from "next/head";
import { ReactNode, useState } from "react";
import Navigation from "components/Navigation/Navigation";
import Header from "components/Header/Header";
import Footer from "components/Footer/Footer";
// import styles from "./MainTemplate.module.scss";

const MainTemplate = ({ children }: { children: ReactNode }) => {
  const [navigationVisibility, setNavigationVisibility] = useState(false);
  return (
    <>
      <Head>
        <title>Newonce blog</title>
        <meta
          name="newonce-blog-example"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setNavigationVisibility={setNavigationVisibility} />
      <Navigation
        navigationVisibility={navigationVisibility}
        setNavigationVisibility={setNavigationVisibility}
      >
        {children}
        <Footer />
      </Navigation>
    </>
  );
};

export default MainTemplate;
