import Head from "next/head";
import { ReactNode } from "react";
import Navigation from "components/Navigation/Navigation";
// import styles from "./MainTemplate.module.scss";

const MainTemplate = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Newonce blog</title>
        <meta
          name="newonce-blog-example"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      {children}
      <footer>footer</footer>
    </>
  );
};

export default MainTemplate;
