export enum Options {
  LOGOWANIE = "Logowanie",
  CLUB = "newonce.club",
  REDAKCJA = "Redakcja",
  BAZA_MUZ = "Baza muzyczna",
  LISTA_HIT = "Lista przebojów",
  PRACA = "Praca",
  FEEDBACK = "Feedback i pomysły",
  PRYWAT = "Polityka prywatności",
  REG_1 = "Regulamin ogólny korzystania z serwisu",
  REG_2 = "Regulamin korzystania z usługi subskypcyjnej newonce club",
}

export enum Categories {
  WSZYSTKO = "Wszystko",
  RAP_PL = "Polski rap",
  KINO = "Kino",
  SERIALE = "Seriale & tv",
  RAP_ZAGRANICZNY = "Zagraniczny rap",
  SPRAWY = "Sprawy",
  OPINIA = "Opinia",
  POP = "Pop",
  ROZMOWY = "Rozmowy",
  TECH = "Tech",
  LAJTOWO = "Lajtowo",
  GAMING = "Gaming",
  NEWONCE = "Newonce",
  ALTERNATYWA = "Alternatywa",
  SPORTOWO = "Sportowo",
  STYL = "Styl",
  ELEKTRONIKA = "Elektronika",
}
